# Generated by Django 4.0.5 on 2022-07-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstable',
            name='is_verified',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='userstable',
            name='token',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
